### ISSUE TITLE
Sales Path might be too long for mobile

### ISSUE THREAD

**Issue by jorgjanke** [salesforce-ux/design-system#130]
The Sales Path might me too long for small devices.
Ideally should be centered around "current"

![image](https://cloud.githubusercontent.com/assets/168846/11611527/c755a362-9b87-11e5-9fa7-665dfd4d5918.png)

QuickFix (better than overflowing)
.slds-tabs--path {
  overflow: hidden;
}

![image](https://cloud.githubusercontent.com/assets/168846/11611540/55158ca8-9b88-11e5-8d18-9777a8c7a08a.png)

**Comment by stefsullrew** [comment]
Hi @jorgjanke, currently Sales Path is not a mobile component. We're actively looking at mobile solutions for a variety of components.

I actually don't think overflow:hidden is a good solution since there would be no way to access the hidden information and you could lose half the sales path. I'll mark this issue as an enhancement request though. :)

**Comment by avaidya** [comment]
Hi @stefsullrew 

Can we change the color of the sales path? Like in the above image, it showing combination of green and blue, Can I change it to dark green instead of blue for last stage? Is there any simple way to do accommodate it?

Thank you,
Amit
