### ISSUE TITLE
Feature Request: Include JavaScript support like Bootstrap library

### ISSUE THREAD

**Issue by DouglasCAyers** [salesforce-ux/design-system#153]
The SLDS design is beautiful, however, there is no built-in javascript support to generate the fancy designs, menus, date pickers, lookup, etc.

To be on par with current design libraries like jquery-ui and bootstrap, I believe adoption of SLDS will be greater for developers if SLDS provided javascript support like those libraries. Or even some variant of SLDS theme that could be plugged in to jquery-ui or bootstrap itself.

There's a lot of us developers that have invested with jquery and bootstrap, and to try to switch to SLDS with zero javascript support is an immediate roadblock and killer.

Thanks for your consideration!

**Comment by stefsullrew** [comment]
Thanks for your request @DouglasCAyers. You're not the first to request this. We're certainly evaluating our options. Stay tuned for a decision. Cheers!

**Comment by fontani** [comment]
I'm using tab drop js for responsive tabs.  I think it can be useful if you plan to add js to the library

**Comment by marcelosomers** [comment]
Not sure if this is the right place, but I'll make my case here for why it would make sense to include some JS libraries. I don't necessarily support Bootstrap, as I think you've done great work building your own framework.

Certain components like the datepicker or lookup probably require some sort of library to use. I'm personally using Kalendae for the datepicker and Twitter Typeahead for the Lookup. Both are fairly customizable, but it's impossible to use the SLDS classes and DOM structure straight out of the box. I'm essentially having to spend a few hours per component to reskin the library version, and it's never quite right. For example, you've got the year dropdown on the datepicker which isn't supported by any libraries I've found.

I like the fact that SLDS is pretty agnostic of libraries for the most part, but it'd be nice if there was a "recommended" library. Ideally something that's framework agnostic (i.e., no jQuery, Angular, or React dependency) and SLDS will support out of the box. Then if you want to use it with your own custom library, you'd have to reskin.

I know this is a huge issue to figure out ("what's the scope of our design system?") and you've gone this current direction because it's much easier.

I look forward to seeing where the team lands, @stefsullrew!

**Comment by akshay0606** [comment]
Hello Everyone,
I tried to use the date picker code from (https://www.lightningdesignsystem.com/components/datepickers/#content), however it doesnt work, do i need to modify something in the date picker code or i need to use a custom date picker from jquery in a visualforce page with lightning css Thanks in Advance!

**Comment by DouglasCAyers** [comment]
@akshay606, correct, you need to provide any and all JavaScript to make the concept functional. SLDS is just the look and feel. 

If you’re developing in Salesforce Platform then make sure to leverage the lightning base components which do just that.
