### ISSUE TITLE
Hiding a grid column causes remaining columns to fill space

### ISSUE THREAD

**Issue by marcelosomers** [salesforce-ux/design-system#163]
I'm building a two column form, where each column uses `.slds-size--1-of-2` to size the column. If I apply the `.slds-hide` class to one column, I'd expect it to disappear, but for the remaining column to still be sized at 50%.

This basically:

```html
<div class="slds-grid">
  <div class="slds-size--1-of-2 slds-hide">
    ...
  </div>
  <!-- This column should still be 50% -->
  <div class="slds-size--1-of-2">
    ...
  </div>
</div>
```

However, the remaining column now fills all the available space. I'm a flexbox newbie still, but this seems to happen due to the `flex-basis: auto` value which triggers the browser to auto-fill the remaining content.

I should be able to work around this, but it'd be nice if the grid supported hiding a column if needed, especially since there are many situations where Salesforce rules cause blocks of content to be shown or hidden. In this case, my left column has one set of fields that get triggered by one rule and the right column gets triggered by another rule, so if the 2nd column is the only one shown, it would be 50% on the left.

**Comment by stefsullrew** [comment]
Hmmm, I just tested that out @marcelosomers, and it's working here. They are retaining their 50% width. Here's a codepen: http://codepen.io/salesforce-ux/pen/342a370eebd63cda4ef9fbe2f9ec5663?editors=1100 Check it and see.

**Comment by marcelosomers** [comment]
Found the issue - I'm using `.slds-col--padded`, which adds `flex: 1 1 auto` that causes it to stretch. Here's my actual code: http://codepen.io/marcelosomers/pen/aNNNNX

I'd like to be able to use `.slds-col--padded` because I want gutters between my two columns of form elements. Am I misusing them?

**Comment by stefsullrew** [comment]
Ahhh, yes. I just copy pasted your code. So I missed the `.slds-col` and `slds-col--padded` effect. 

In our grid system, we have a class that doesn't let the grid cell grow. `.slds-grow--none` sets the `flex-grow: 0;`. That fixes the issue here. If you're using sizing (and not allowing auto-sizing), then I'd say you could either safely apply it to both grid cells from the beginning or dynamically apply it to the cell that is visible when the other is hidden. Which ever suits your needs.
http://codepen.io/salesforce-ux/pen/vGGypG?editors=1100

**Comment by marcelosomers** [comment]
Worked perfectly! Thank you for pointing that out.

Just as an FYI for anyone in the future, the actual class is `.slds-grow-none` - I'm not sure if you're changing it to be more BEM-y in a future release.

**Comment by stefsullrew** [comment]
Thanks for correcting my class name. I think we stuck with a single dash since you wouldn't use `.slds-grow` with `.slds-grow-none` so it's not a modifier. That being said, you also don't need to add `.slds-col` along with `.slds-col--padded`, so yea... Naming is hard and we still have some inconsistencies we may need to work out.
