### ISSUE TITLE
Multi-Select (in progress prototype) isn't responsive

### ISSUE THREAD

**Issue by marcelosomers** [salesforce-ux/design-system#165]
Looks like the [Multi-Select](https://www.lightningdesignsystem.com/components/forms/#multi-select) is in prototype stage as of 1.0.0, but one oddity I noticed is that it's a fixed width. 

Right now I'm including it in a two column responsive form, so as the page grows or shrinks the boxes stay the same width, which is more of an issue as the page gets smaller than the fixed width. Obviously some thinking would need to go on here since side by side wouldn't work at smaller sizes.

Anyways, totally understand this isn't finalized and you're probably aware, but I thought I'd throw it in here in case you hadn't caught it!

**Comment by brandonferrua** [comment]
@marcelosomers thanks for raising this point. Hopefully we can get it out of prototype for this next release! Since the multi-select picklist has a particular set of intended functionality such as drag & drop, re-ordering of items, etc. The complexity of the component and not having a clear understanding of where and when the component would be used within the application caused us to settle on a fixed with for the time being.

If you need a quick workaround for using this component. Wrap the component in `<div class="slds-scrollable--x" />`

**Comment by stefsullrew** [comment]
I should add, only wrap it if you're using it in desktop. `.scrollable--x` does not work in UIWebview (S1). The "pull to refresh" hijacks it. But for regular responsive desktop (and perhaps mobile outside of Webview), you're fine.
