### ISSUE TITLE
CSS class names need refactoring

### ISSUE THREAD

**Issue by jmaikeru** [salesforce-ux/design-system#168]
`--` in a class name causes errors when you attempt to comment out an element with the offending class.

For example: `slds-p-top--medium`

`--` is invalid in XML comments. SF markup is XML. :fire:

**Comment by kaelig** [comment]
Thank you for using SLDS, @jmaikeru. I recommend that changing the class name instead of commenting it. e.g. `slds-p-top--medium` :arrow_right: `COMMENTED-p-top--medium`. it should do the trick!

**Comment by jmaikeru** [comment]
@kaelig you misunderstand what the issue is

```[ERROR]: markup://c:TimeEntries:50,55: ParseError at [row,col]:[51,55]
Message: The string "--" is not permitted within comments.: Source
```

Yes, I know you're using BEM- this seems incredibly short-sighted given the primary platform for this is Salesforce- and attempting to comment out an element that has a double hyphen causes the page to fail to compile.

**Comment by jmaikeru** [comment]
```xml
<!--     <div class="container slds-p-top--medium">
        <div id="list" class="row">
            <aura:iteration items="{!v.timeEntries}" var="entry">
                <p>{!entry.Start__c}, {!entry.End__c}, {!entry.Description__c}</p>
            </aura:iteration>
        </div>
    </div> -->```

**Comment by kaelig** [comment]
My bad, I thought the use case was "comment a class name". 

Thank you so much for bringing this up, we will take it under consideration and get back to you very soon.

**Comment by stefsullrew** [comment]
Hi @jmaikeru, can you please fill us in on what SF platform you're building on? There are many ways to compile. If you're an internal dev, I invite you to comment on the Chatter group. Cheers!

**Comment by jmaikeru** [comment]
@stefsullrew not an internal dev.

```xml
<!--     <div class="container slds-p-top--medium">
        <div id="list" class="row">
            <aura:iteration items="{!v.timeEntries}" var="entry">
                <p>{!entry.Start__c}, {!entry.End__c}, {!entry.Description__c}</p>
            </aura:iteration>
        </div>
    </div> -->
```

This compiles in Visualforce (both metadata and tooling)
This fails to compile in Lightning (both metadata and tooling)

The VF XML parser isn't as strict (or correct) as the Lightning one- you can't have `--` in an XML comment. It's part of the spec. This effectively means you'll be unable to comment any elements using the offending BEM-style classes in XML/XHTML based markup (depending on how strict the compiler is).

It's invalid XML. Bootstrap does pretty well with just `-` instead of `--`. I guess it's just a matter of weighing the pros of using BEM- against the cons of creating invalid XML whenever an element with a class is commented out.

**Comment by stefsullrew** [comment]
Hi @jmaikeru - We are actively working on a solution internally. For now though, I can give you a kind of "dirty" way to do it (though it works, you can't use your typical key command for commenting).

```<span style="display: none;"><![CDATA[

    this is sub-optimal but works for now

    <p class="foo--bar">something to comment out</p>

]]></span>```

So essentially, the `CDATA` comment makes the XML ignore the elements, but it won't actually "comment them out" since our engine will still show the `CDATA` comment as text. Adding the `display:none;` will then also remove it from the DOM. Yes, it's a temporary hack. Hope it helps.

**Comment by JohnHeadIV** [comment]
I just wanted to see if this is getting any attention. Having to modify class names in comments when developing in Lightning has already lead us to some wasted time tracking silly errors.

**Comment by caridy** [comment]
hey guys, this is more complex and will require some rework on the internals of the server-client communication that we have to mark CDATA comments in the process. I have a less nasty version of the hack:

1. Create a new empty component in your org, saying:

`myorg/comment/comment.cmp`:

 ```xml
<aura:component></aura:component>
```

2. Use the `comment` component from your org in conjunction with the CDATA comment to prevent evaluation and display, e.g.:

```xml
<myorg:comment>
      <![CDATA[<p class="foo--bar">foo</p>]]>
</myorg:comment>
```

**Comment by stefsullrew** [comment]
Good news, we now have a workaround. Rather than using a regular comment syntax, you can use:
 
    <?ignore <div class="slds--abc"/> ?>
 
We've added <?ignore … ?> as a non-existing XML processing instruction (see https://www.w3.org/TR/REC-xml/#sec-pi). Processing instructions are not part of the document data, just like comments. It’s up to the application to decide what to do, and we've added code to ignore the "ignore" instruction. 

You can add a custom key command in your favorite editor to apply this.

This is a little hack and I hear that we are going to have a better solution in the future, but for now it should make your job easier, and that's what matters most.
