### ISSUE TITLE
[ENHANCEMENT] DRY scss variables on design-tokens

### ISSUE THREAD

**Issue by 3den** [salesforce-ux/design-system#185]
Currently it is very hard to customize the colors given on design-tokens.sass because there is way too much duplication of the same values in different vars. It is a good thing that we have granularity so that people can override one var without messing up with an other... But when you want to change the color scheme the goal is to make it consistent and this duplication makes the project much harder to maintain and customize.

Bootstrap solves this issue (https://github.com/twbs/bootstrap/blob/master/less/variables.less) by having a few core variables receive a hardcoded value and most of its variables just reuse those main variables without having to duplicate the same value. 

This approach would make SLDS much easier to customize, e.g.

``` scss
$color-brand-dark: rgb(0, 112, 210) !default;
$color-brand-darker: darken($color-brand-dark, 10%) !default;

// Currently all this variables, and much more, have exactly the same hardcoded value...
// We can improve this by having the rgb value just in one varible an let all other vars use it.
$color-border-button-brand: $color-brand-dark !default;
$color-text-icon-brand: $color-brand-dark !default;
$color-background-modal-brand: $color-brand-dark !default;
$color-border-brand-dark: $color-brand-dark !default;
...

```

**Comment by kaelig** [comment]
Thanks for that feedback. We're working on a solution to make token management more comprehensive so… watch this space!

**Comment by istiti** [comment]
@kaelig hi there, it's been a long time this issue open 


Does salesforce team actually consider problem? (its been tagged as "enhancement" since March 2016)

Is there any action/document/roadmap being taken to make it easier to change design (color at all)

Is this a better organisation of scss  in the next month? 6 months? year?

If not any documentation of where can we doanload lignthing design ONLY for web  (i mean scss/icon/css/icon only) because actually salesforce package on npm is very complet  with a lot of  possiblity while I need only web  ?

Are they still researching the answers to the above questions? 


/cc @ishakasliwal

**Comment by stefsullrew** [comment]
In the next release, Salesforce is offering a way for customers to change their branding colors. Have you had a look at My Salesforce?

**Comment by istiti** [comment]
Apologizes me I don’t know what is my salesforce any link? 

Cc @stefsullres
