### ISSUE TITLE
Prompt Close Button

### ISSUE THREAD

**Issue by FabienTaillon** [salesforce-ux/design-system#210]
Prompt Component markup has a close button in it:

```
<button class="slds-button slds-button--icon-inverse slds-modal__close">
  <svg aria-hidden="true" class="slds-button__icon slds-button__icon--large">
    <use xlink:href="/assets/icons/action-sprite/svg/symbols.svg#close"></use>
  </svg>
  <span class="slds-assistive-text">Close</span>
</button>
```

However, no button is displayed. So I don't know if the close button is supposed to be displayed and is not, or if this part of the markup is just useless.
Not that important, but letting you know :)

https://www.lightningdesignsystem.com/components/notifications/#prompt

**Comment by kaelig** [comment]
Merci Fabien for reporting this.

This is a good point, we will discuss this and come back to you with an answer.

**Comment by stefsullrew** [comment]
Yes, modals come with the close button by default (in the world of components). So I hid it for consistency since in this use case, the designers want the customer to be forced to specifically OK the message in the prompt, not just X it out. 

That said, if you're using this in a place where you control the DOM, you could remove it altogether. (And I suppose I could do that here but leave the CSS class.) Thanks for the memory? ;)

**Comment by SiTaggart** [comment]
Yeah, I'd be tempted to remove completely given the intended interaction is you must hit the "OK" button. Otherwise it's kind of confusing.

Additionally, the role could be switched to `role="alertdialog"` for a more relevant meaning. https://www.w3.org/TR/2011/CR-wai-aria-20110118/roles#alertdialog

**Comment by SiTaggart** [comment]
This has now been addressed in the latest release 
https://www.lightningdesignsystem.com/components/notifications/#flavor-prompt

Thanks for pointing it out.
