### ISSUE TITLE
Feature Request: Fixed Header Row for slds-table

### ISSUE THREAD

**Issue by pranavraulkar** [salesforce-ux/design-system#227]
It would be a good feature to make the table header fixed. This helps especially for tables where we have large data-set and many columns. While scrolling, it might become difficult to remember column order. A simple class on table (something like slds-table--fixed-header) which makes header fixed for vertical scroll would is much needed.

**Comment by stefsullrew** [comment]
Thanks for the request, @pranavraulkar ... We'll evaluate. 

Cheers

**Comment by jziesing** [comment]
I agree

**Comment by sebastiankessel** [comment]
Has there been any movement on this?

**Comment by kanwalpreet-singh** [comment]
It can be achieved by standard way, please look at [this](https://iotacloud.wordpress.com/2017/08/18/slds-framework-data-table-with-fixed-header/) link. Also i posted code example code on github url [this](https://github.com/kanwalpreet-singh/salesforce/blob/master/Data-table%20with%20fixed%20header.html). I am able to achieve this by using standard design system classes.

**Comment by stefsullrew** [comment]
Hah... you're a good sleuth, aren't you, @kanwalpreet-singh? ;)

Yes, the classes exist. They were created for internal use. However, there may be a bit more that has to be done for more complex data-tables. This is why, at this time, we aren't planning to support it externally. There can be a height needed so that the table can scroll and the fixed header stays in place (that would have to be calculated with JS). If your table scrolls horizontally, you'd need JS to move the headers along with it. 

For the reasons of "If you have this need, then you need to do that", which is complex, we do have classes, but they're unsupported or "use at your own risk". I thought I had a CodePen that I could share and you could at least see it in action, but I have been unable to find it. :(  If I can find it (or find time to make a new one), I'll share it. But I'll be sharing it from one engineer to another... not because we're supporting it. Fair?

**Comment by kanwalpreet-singh** [comment]
You are truly right...i implemented the javascript solution(using tranform 2d/3d and static positions Interenet Explorer approach is different) for my company's project that's an AppExchange Product (sorry cant share due to company policies), it works same as Salesforce Ligtning supports using aura . On the other hand i was looking alternate solution so just come up with this one.
