### ISSUE TITLE
Multi Scope Lookup doesn't preserve focus

### ISSUE THREAD

**Issue by Guria** [salesforce-ux/design-system#23]
https://www.lightningdesignsystem.com/components/lookups/#multi-scope
* click in lookup

focus border blinks and disappears

**Comment by brandonferrua** [comment]
Thanks for reporting @Guria 

I will be removing the focus attribute from the container of the multi-scope lookup. Our design language indicates that two focus states are available within this component, one on the 'scope' dropdown, which displays the menu via the focus interaction AND one of the text input which displays an additional dropdown menu on the focus interaction.

With the dropdown menu appearing on focus, there is no need for the focus border anymore.

Also note, that these focus events come from additional javascript and not from the CSS. Since we are not supporting a javascript solution at the moment, the live example does not showcase this interaction.

**Comment by kaelig** [comment]
Closing this as the Multi Scope lookup was removed from the Design System in v2.0.0.
