### ISSUE TITLE
Checkbox Webdriver testing issues

### ISSUE THREAD

**Issue by jorgjanke** [salesforce-ux/design-system#269]
In the markup, the input element has the id.
In the webdriver, I locate the input element by id and then click.

In the recent versions of Chrome and Firefox as well on Android, this fails as the browser basically checks if the input element is visible.

The error messages:
FF:
org.openqa.selenium.WebDriverException: Element is not clickable at point (612, 462). Other element would receive the click: <span class="slds-checkbox--faux"></span>

Chrome:
org.openqa.selenium.WebDriverException: unknown error: Element is not clickable at point (596, 452). Other element would receive the click: <nav class="slds-grid slds-wrap">...</nav>

Android:
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)

Works sometimes on Mac FF (development box), but consistently fails in SauceLabs
Works in IE/Edge/Safari/iOS (probably until they upgrade their WebDriver).

Any suggestions?

**Comment by kaelig** [comment]
Thanks for reporting this @jorgjanke. Also, it's great to see you're automating user flow testing with WebDriver ❤️ 

Here's the code of a basic checkbox.

```html
<div class="slds-form-element">
  <div class="slds-form-element__control">
    <label class="slds-checkbox">
      <input type="checkbox" name="options" id="checkbox-01" />
      <span class="slds-checkbox--faux"></span>
      <span class="slds-form-element__label">Checkbox Label</span>
    </label>
  </div>
</div>
```

- The checkbox input is hidden, and this might be why the browsers refuse to click it.
- Getting webdriver to click `<label class="slds-checkbox">` could work, since it's visible.

To make this label easier to select in the DOM, you could try this:

```diff
- <label class="slds-checkbox">
+ <label class="slds-checkbox" for="checkbox-01">
```

From there, it allows for this: `document.querySelector('label[for="checkbox-01"]')` (or however your framework selects elements from the DOM).

I hope this helps, let me know how this goes for you and if you found a better workaround!

**Comment by jorgjanke** [comment]
rather than a querySelector I use
`<label class="slds-checkbox" for="checkbox-01" id="checkbox-01-lbl">`
hoping you had a better solution :-)

**Comment by kaelig** [comment]
Thanks for the feedback. Feel free to reopen this issue if needed!
