### ISSUE TITLE
SLDS202 for Lightning Components (without customized scoped CSS)

### ISSUE THREAD

**Issue by azalizh** [salesforce-ux/design-system#276]
I've been using SLDS103 for Lightning Components, installed via Unmanaged Package in Salesforce. I want to [update](https://www.lightningdesignsystem.com/downloads/) it. _It is no longer necessary to add a static resource for Lightning Components for Lightning Experience._ I got it, but I want to use it for prototyping components in a standalone Lightning Application (/c/myApp.app) and not using in a development process in LEx.

Previously 
`<ltng:require styles="/resource/SLDS103/assets/styles/salesforce-lightning-design-system-ltng.css" />`
In Design System Zip version (of SLDS202) it is
 `... /resource/SLDS103/assets/styles/salesforce-lightning-design-system.css`
so without `-ltng`. So probably, Salesforce have different versions for LTNG, what is proven in _SLDS for with customized scoped CSS file_ where are 3 versions, also
 `... /resource/SLDS103/assets/styles/salesforce-lightning-design-system-vf.css`
so with `-vf`.

I tried using default `salesforce-lightning-design-system.css` but I came across an issue with fonts (Salesforce Sans not available for labels, but in input fields applied).
It's impossible to download SLDS package from [CSS-Customizer](https://tools.lightningdesignsystem.com/css-customizer) without Scoping Class.

Back to the entry point: 
**where can I download SLDS202 directly for LTNG and for VF, without customized scoped CSS file?**

**Comment by stefsullrew** [comment]
We provide the option for the regular CSS or scoped CSS for both VF and LTNG. There is not a special CSS file for VF or LTNG that is "not scoped" because LTNG uses the same file as SLDS.css and VF has special needs that require the scoping.

Now, that said, you have a couple ways of working around this. Currenlty, if you are building a my.app, you'll need to download the custom scoped file here: https://tools.lightningdesignsystem.com/css-customizer It's very easy to add a div wrapper with your custom scope at the top level of your my.app. Even if you build Lightning Components and drop them into your my.app, they'll be taken care of.

*Forward looking statement* In future releases, you'll be able to automatically receive SLDS without adding it as a static resource in my.app. But not quite yet.

Cheers

**Comment by azalizh** [comment]
Thank you Stephanie for the workaround. I added in my `<aura:application>`
```
<div class="my-company">
   <div class="slds">
    ...
   </div>
</div>
```

and it worked with
`<ltng:require styles="/resource/SLDS202myCompany/assets/styles/salesforce-lightning-design-system-ltng.css" />`

I still don't get why 

> There is not a special CSS file for VF or LTNG that is "not scoped" because LTNG uses the same file as SLDS.css

if we have 
* `salesforce-lightning-design-system-ltng.css`
* `salesforce-lightning-design-system.css`

With this without `-ltng`, SalesforceSans font doesn't apply for labels in my custom LTNG/aura app. Maybe LEx (Lightning Experience) uses it for LTNG.

**Comment by stefsullrew** [comment]
In your code example above, if you have done a custom scope, you no longer need the `<div class="slds">` in addition.

As to your question... if you're using the non-scoped version — OH! I think I know what it is. I saw this another time.

Inspect and see if there's a reset being added that changes the fonts. I think there is one in my.app (It will be removed when they do some work there later). If so, for now, you can override that reset by resetting the fonts yourself for headings (I think that's the main use case).

**Comment by kaelig** [comment]
In Winter ’17, the Design System's CSS is available without the need of a scoping class.

We've documented how to use this here: https://www.lightningdesignsystem.com/platforms/lightning/

I'll close this for now, but feel free to reopen it if you're still encountering this issue.
