### ISSUE TITLE
Styling is messed up when datepicker is used inside a table

### ISSUE THREAD

**Issue by sameernmiraj** [salesforce-ux/design-system#297]
When we use the datepicker inside a table the styling is going completely off. The `<table>` element inside the datepicker is getting styled as per the parent table rather than having its own styling. 

Below code (and screenshot) should be able to give you guys an idea of what I am talking about.

``` html
<table class="slds-table slds-table--bordered slds-table--cell-buffer">
  <thead>
    <tr class="slds-text-heading--label">
      <th scope="col">
        <center>
            <div class="slds-truncate" title="Some date">Some Date</div>
        </center>
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td>
            <slds-date></slds-date><!--Exact code available on SLDS website for datepicker-->
        </td>
    </tr>
  </tbody>
</table>  
```

![image](https://cloud.githubusercontent.com/assets/20188751/17735573/a0623b3e-64a0-11e6-8d74-03c6686d16e2.png)

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System and reporting this, @sameernmiraj!

We'll look into it and let you know when this is fixed.

**Comment by kaelig** [comment]
The workaround is to not use the datepicker inside a table, and instead appending the element outside and position it using JavaScript. Thank you for your understanding!

**Comment by jeffrey008** [comment]
Hello @kaelig , would you give us some example on this issue?
I am using  `<lightning:input type="date"/> ` in my table and the styles and messed up. I still cannot think of a workaround for this.

**Comment by rapsacnz** [comment]
The solution is to use my datepicker, which is designed to handle being in a table. Here's the link: https://github.com/rapsacnz/DatePicker - If you are going to use, wait a couple of hours, as I'm just about to push the table improvements to github.

**Comment by ruslan-kurchenko** [comment]
I've met the same issue.

![screen shot 2018-09-05 at 5 18 41 pm](https://user-images.githubusercontent.com/29373749/45099378-c74b9a00-b12f-11e8-8270-89c5996d468c.png)

And guys, why did you close the unresolved issue. We have a workaround to _"not use the datepicker inside a table"_, but is it a solution?

**Comment by rapsacnz** [comment]
@ruslan-kurchenko My version looks and works similarly to the official one... and it works inside a table (it's actually an easy fix - you just have to reset a few styles, no idea why the team here can't do it for the built in one)

**Comment by ruslan-kurchenko** [comment]
@rapsacnz your calendar is really nice, thank you for the suggestions. But unfortunately, I can't add your implementation to the project I work on. That is why I'm wondering why they can't resolve that natively.

**Comment by SiTaggart** [comment]
Hi folks!

Thanks for your continued interest in this project. Unfortunately, we're going to reiterate the suggestion made by Kaelig back in January 2017.

We strongly advise that you don't place a date picker as a child to any element in a data table. This is due to accessibility usability issues with nested table elements, and not because we don't want to fix the styling.

Due to the accessibility concerns, we'd really like to not add CSS to the framework to address an issue we don't have a use case for as it will cause unnecessary bloat to the CSS file size. 

We're sorry if that's not ideal for you, but we really feel that nested tables are a bad idea.

**Comment by rapsacnz** [comment]
@ruslan-kurchenko looks like you are stuck with me... ;)

**Comment by maximelets** [comment]
you can use css to fix it(little ugly hack)
`.THIS table td lightning-calendar td {
    padding: 0 !important;
    border-top: none !important;
}`

**Comment by julianACL** [comment]
@SiTaggart one use case would be inline editing of date fields in data tables.

**Comment by gonardfreeman** [comment]
it is 2019 and still no help...

**Comment by DhivyaP89** [comment]
Hi ,

I am also facing the same issue . When we remove the styling of the parent html table slds-table slds-table_bordered slds-table_fixed-layout this issue is gone .But still not able to allign the datepicker inline with that column. Using input is not accepted since other date pickers are in lightning style

**Comment by guptaa19** [comment]
has anyone found a resolution for this problem yet ?

**Comment by jeffrey008** [comment]
Stop messing around with SFDC and move on. Change a job or sth. They don't really care about this anymore.

**Comment by rapsacnz** [comment]
Haha @jeffrey008 esp since I fixed this issue about 2 years ago in my custom datepicker component: https://github.com/rapsacnz/DatePicker

**Comment by MuriloKakazu** [comment]
New year, same problems. As usual... 😆 

This should be tagged as `wontfix` at least
