### ISSUE TITLE
horizontal list with dividers on multiple lines

### ISSUE THREAD

**Issue by jorgjanke** [salesforce-ux/design-system#33]
When rendering a horizontal list with dividers, everything is fine the content fits on one line

                <ul class="slds-list--horizontal slds-has-dividers">
                  <li class="slds-list__item">Dart Language Overview</li>
                  <li class="slds-list__item">Development environment, Tooling</li>
                  <li class="slds-list__item">Lightning Design System</li>
                  <li class="slds-list__item">Demo</li>
                </ul>

if the content does not fit on one line, the items themselves are adjusted with the dots as the last character in the previous entry.

The expectation is that the list items are wrapped e.g.

    * Dart Language Overview * Development Environment, Tooling
    * Lightning Design System * Demo

although would be fine if wrapped on word break, e.g.

    * Dart Language Overview * Development Environment, Tooling * Lightning 
    Design System * Demo

![image](https://cloud.githubusercontent.com/assets/168846/10118914/24bc288e-643b-11e5-8876-08a671ceafd2.png)

**Comment by stefsullrew** [comment]
Hi @jorgjanke ... Since the horizontal lists are flexbox, they will remain on one line (as you saw) unless you give them further permission to wrap. If you add the `slds-wrap` class to the `<ul>`, it will wrap when it exceeds the width of its parent. 

Just be aware, the dots between list items are following the list item, not preceeding it. So in your example above, it will wrap "per li" but the dot will follow the last one on the row. (The very last li doesn't get a dot following it on the last row.)

Does this solve your issue? (We need to document that in the list area... currently it's in the grid docs.)

**Comment by jorgjanke** [comment]
Hi Stephanie,

My point was that the layout classes used should not be dependent on the number of items or width available or width/length of the individual items. 
I.e. the markup should work if there are one, two or many li items. Also as this is dependent on available width, I would have to have to change the markup if the width changes.

I guess the options are either 
- to state the restriction "only works if all the content fits into a single line"
or 
- change the markup that it works independent of volume/length
or
- change the scss to be content/size independent

Cheers,
Jorg

**Comment by stefsullrew** [comment]
I hear you. What I'm saying is that the framework wants you to "opt in" to extra functionality. If you always want your horizontal lists to wrap across the board, you don't need to change your markup if you have more items or a width change. You simply always use the classes:
`<ul class="slds-list--horizontal slds-has-dividers slds-wrap">`

From thereon, whether your lists are short or need to wrap, they'll give you the desired behavior. 

What we're trying to avoid is placing properties onto components that then have to be overridden if someone does not desire the wrapping behavior. So it's an "opt in" rather than "opt out" thing. Does that make sense?

We need to make that more clear in our documentation.
