### ISSUE TITLE
Checkbox in Horizontal Layout followup

### ISSUE THREAD

**Issue by jorgjanke** [salesforce-ux/design-system#40]
I saw your solution to #11 in v0.9.2

The approach is _"unusual"_ as checkboxes usually do not have multiple labels - only if you represent multi-select as checkboxes.  Also I think, it should be possible to flip between horizontal and stacked layout - i.e. with the same html code.

Suggestion:
```
<div class="slds-form-element">
  <div class="slds-placeholder"><!-- empty --></div>
  <label class="slds-checkbox"> .... </label>
</div>
```
where the 
**slds-placeholder** basically acts like a form-element__label
- display: inline-block if within _form--horizontal_ otherwise none
- width 33%

and adding to **slds-checkbox**  if within _form--horizontal_
- width: calc(66% - (0.75rem * 2));
- text-align: left

... or

```
<div class="slds-form-element">
  <div class="slds-form-element__label"><!-- empty --></div>
  <label class="slds-form-element__control"> .... </label>
</div>
```
Advantage:
- same html structure as normal fields, just with empty label
- fewer, less complex css changes (just handling empty label in stacked)

**Comment by brandonferrua** [comment]
Even though you may have one element, it is recommended for accessibility to still have a `<legend>` that describes the content within the `<fieldset>`.  

Now with that said, having a `<legend>` describe the `<fieldset>` is optional because the checkbox is wrapped within a `<label>` so it's valid and accessible. So you can have the structure like so, if you have one checkbox element:

```
<fieldset class="slds-form-element">
  <div class="slds-form-element__control">
    <label class="slds-checkbox" for="opportunities-ownership">
      <input name="default" type="checkbox" id="opportunities-ownership" />
      <span class="slds-checkbox--faux"></span>
      <span class="slds-form-element__label">All opportunities owned by you</span>
    </label>
  </div>
</fieldset>
```

or

```
<fieldset class="slds-form-element">
  <span class="slds-form-element__label slds-form-element__label--top slds-assistive-text">
    <legend>Describing the Content within this fieldset</legend>
  </span>
  <div class="slds-form-element__control">
    <label class="slds-checkbox" for="opportunities-ownership">
      <input name="default" type="checkbox" id="opportunities-ownership" />
      <span class="slds-checkbox--faux"></span>
      <span class="slds-form-element__label">All opportunities owned by you</span>
    </label>
  </div>
</fieldset>
```

The `.slds-assisstive-text` will hide it visually but available to screen readers.

Having multiple checkboxes and radios is common, especially in complex forms so the markup structure should accommodate for such.

You raise a strong point though that our documentation should be more thorough. We'll be making our documentation better over time.
