### ISSUE TITLE
Property display:block on <summary> removes the disclosure triangle

### ISSUE THREAD

**Issue by agnitsevich** [salesforce-ux/design-system#424]
Lightning Design System forces `display:block` property on the `summary` tag.
https://github.com/salesforce-ux/design-system/blob/master/ui/vendor/_normalize.scss#L45,L47

> article, aside, details, figcaption, figure, footer, header, hgroup, main, menu, nav, section, **summary** {
>     display: block;
> }

Which, according to HTML standard, removes the disclosure triangle:

https://html.spec.whatwg.org/multipage/rendering.html#the-details-and-summary-elements
https://bugzilla.mozilla.org/show_bug.cgi?id=1283989

**Comment by stefsullrew** [comment]
Interesting find, @agnitsevich ... Perhaps we should file this on the normalize.css project since this comes from them?

Since some of these HTML5 elements are still unknown to IE11/Edge, we still need to give them layout. But reading David Baron's comment in the bug, it seems as if `summary` should be given `display:list-item` instead of `block`.

**Comment by stefsullrew** [comment]
Oh wait. I just went over to file that bug on Normalize, and it appears Jon has fixed it. @kaelig, can you see about upgrading us to normalize 5.0? :) He's made that change there.

**Comment by kaelig** [comment]
👍 We can definitely look into it.

We're a couple major versions behind - so we'll need to provision extensive cross-browser and cross-platforms (Lightning / Visualforce / Off-platform) testing for an upgrade.

Note: we also have a custom version of normalize, edited for Visualforce usage. Differences between the two are undocumented.

Here are all the things we'll need to consider compared to where we are:

### 5.0.0 (October 3, 2016)

* Add normalized sections not already present from
  https://html.spec.whatwg.org/multipage/.
* Move unsorted rules into their respective sections.
* Update the `summary` style in all browsers.
* Remove `::placeholder` styles due to a bug in Edge.
* More explicitly define font resets on form controls.
* Remove the `optgroup` normalization needed by the previous font reset.
* Update text-size-adjust documentation  for IE on Windows Phone
* Update OS X reference to macOS
* Update the semver strategy.

### 4.2.0 (June 30, 2016)

* Correct the `line-height` in all browsers.
* Restore `optgroup` font inheritance.
* Update normalize.css heading.

### 4.1.1 (April 12, 2016)

* Update normalize.css heading.

### 4.1.0 (April 11, 2016)

* Normalize placeholders in Chrome, Edge, and Safari.
* Normalize `text-decoration-skip` property in Safari.
* Normalize file select buttons.
* Normalize search input outlines in Safari.
* Limit Firefox focus normalizations to buttons.
* Restore `main` to package.json.
* Restore proper overflow to certain `select` elements.
* Remove opinionated cursor styles on buttons.
* Update stylelint configuration.
* Update tests.

### 4.0.0 (March 19, 2016)

* Add the correct font weight for `b` and `strong` in Chrome, Edge, and Safari.
* Correct inconsistent `overflow` for `hr` in Edge and IE.
* Correct inconsistent `box-sizing` for `hr` in Firefox.
* Correct inconsistent `text-decoration` and `border-bottom` for `abbr[title]`
  in Chrome, Edge, Firefox IE, Opera, and Safari.
* Correct inheritance and scaling of `font-size` for preformatted text.
* Correct `legend` text wrapping not present in Edge and IE.
* Remove unnecessary normalization of `line-height` for `input`.
* Remove unnecessary normalization of `color` for form controls.
* Remove unnecessary `box-sizing` for `input[type="search"]` in Chrome, Edge,
  Firefox, IE, and Safari.
* Remove opinionated table resets.
* Remove opinionated `pre` overflow.
* Remove selector weight from some input selectors.
* Update normalization of `border-style` for `img`.
* Update normalization of `color` inheritance for `legend`.
* Update normalization of `background-color` for `mark`.
* Update normalization of `outline` for `:-moz-focusring` removed by a previous
  normalization in Firefox.
* Update opinionated style of `outline-width` for `a:active` and `a:hover`.
* Update comments to identify opinionated styles.
* Update comments to specify browser/versions affected by all changes.
* Update comments to use one voice.

---

### 3.0.3 (March 30, 2015)

* Remove unnecessary vendor prefixes.
* Add `main` property.
