### ISSUE TITLE
Are there examples of File Selector in a selected state?

### ISSUE THREAD

**Issue by kevinberonilla** [salesforce-ux/design-system#440]
This is more of a question/request than an issue. I'm building out a File Selector (https://lightningdesignsystem.com/components/file-selector/#flavor-files-file-selector-files) as a Lightning Component and noticed the examples don't include a state where a value is set, displaying the filename before form submission. Are there examples of this state anywhere, or is there another approach that the design team suggests?

**Comment by ishakasliwal** [comment]
@kevinberonilla Thanks for the question.

@owenschoppe Do you have any input on this?

**Comment by owenschoppe** [comment]
I'm assuming you mean after a file has been selected?

Files should be uploaded immediately- use the progress indicator from
files. At that point use a files preview/list item component depending on
context. Cameron Reed will have more info.

Sent from mobile

On Apr 17, 2017, at 2:56 PM, Isha Kasliwal <notifications@github.com> wrote:

@kevinberonilla <https://github.com/kevinberonilla> Thanks for the question.

@owenschoppe <https://github.com/owenschoppe> Do you have any input on this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/salesforce-ux/design-system/issues/440#issuecomment-294605879>,
or mute the thread

**Comment by kevinberonilla** [comment]
Hi @owenschoppe, this is exactly what I needed to know. Thanks for the guidance!
