### ISSUE TITLE
Error in class names for scoped tabs

### ISSUE THREAD

**Issue by matejp84** [salesforce-ux/design-system#450]
There is an error in naming classes for scoped tabs in SLDS.

On webpage where you have example code everything is written with with: 
slds-tabs_scoped

but those classes doesn't exists in CSS, instead it should be: 
slds-tabs--scoped

Also all nested and children classes are names wrongly.

**Comment by srohde** [comment]
We have updated the BEM syntax in our Summer '17 release.
The new syntax is using an underscore "_" instead of the former double dash "--" syntax.
This is a backwards compatible change.

Please refer to the previous documentation (https://archive-2_2_2.lightningdesignsystem.com/
) until your Salesforce instance will get the new Summer '17 release.
