### ISSUE TITLE
Date/Time Input Field 📆  🕚

### ISSUE THREAD

**Issue by tylerzika** [salesforce-ux/design-system#460]
The date/time input field is a standard field type when creating a custom field. Why is there not a Light Design System component for this standard field type?

**Comment by JohnHeadIV** [comment]
I would view this as an extension of  #393 Date/Time input is another example of a compound field in specific use cases. I would mention though that <lightning:input> not present special formatting for specific <input> types. I know that lightning component != SLDS but...  I would also add its interesting that their is a Datepicker styling but I don't believe any mention of how it should work in conjunction with overall form layouts.

**Comment by ishakasliwal** [comment]
@tylerzika Thanks for sharing your input. Due to the high volume of component requests we receive, on top of maintaining existing components, we work on a priority order per release. I'll share your feedback with the team, and once/if we are able to prioritize it, we will work on adding a date/time input field.
