### ISSUE TITLE
Checkbox with disabled state checkmark color

### ISSUE THREAD

**Issue by Lokret** [salesforce-ux/design-system#512]
When checkbox has checked value in a bunch of disabled, then color of checkmark is white. And in some combination of background colors it becomes less visible.

Any plans to fix it?

![invisible checked mark](https://user-images.githubusercontent.com/7910788/32059745-bd36e56c-ba75-11e7-860b-76fb3010c551.png)

**Comment by ishakasliwal** [comment]
@SiTaggart Can you speak to the color contrast here, and whether you think this qualifies as a bug on our end?

**Comment by SiTaggart** [comment]
Disabled controls don't need to meet colour contrast requirements. Having said that, there's no harm in still trying to make it visible or easier to see. 

I'm sure someone internally wanted to fix these up too because it impacted their specific use case. Can't remember who

**Comment by engai** [comment]
Hi @Lokret, a fix for this is on the roadmap and should be released with 2.7.0 (Winter-19)

**Comment by istiti** [comment]
@engai any reason why team need half year to fix issue like that?  
Thanks appreciate

**Comment by engai** [comment]
Hi @istiti, thanks for your question.

Our team runs on the Salesforce release cycle which sees a release 3 times a year (Winter, Spring, Summer). Much of our priorities fall under the scope of requests that teams need to create their new features. As you imagine, this leaves us with a lot of feature requests and bugs each release, and these remain the highest priority for us as a team. In addition to this cadence, we have strict criteria on what may go into a minor or patch release. Lastly, since we are a source available project, our work is not made available until the release date, thought it may be done on our end. 

Lots of variables are involved in explaining why an issue like this may see a release date that is later than expected, but these are a few.

**Comment by engai** [comment]
@istiti Thanks for sharing your concerns. We hope to get to a point where we can make updates within the week to the version that we make available to the public. However, that isn't the case today since, as i've said earlier, there are very strict rules around what changes may enter into a past release. Since our framework is used in the Salesforce product, you can imagine that there are strict criteria around changes that will have an affect on all Lightning customers

**Comment by engai** [comment]
Hey folks, this has been resolved with https://github.com/salesforce-ux/design-system/commit/8614d1c0c21430bf6be7675978b2d61689b5c040
