### ISSUE TITLE
Make the docs searchable

### ISSUE THREAD

**Issue by keirbowden** [salesforce-ux/design-system#52]
Can you add search functionality to the docs at : https://www.lightningdesignsystem.com/ - often I'd like to find the usage/definition of a specific style class and being able to search for that from the page would be great. Thanks!

**Comment by FabienTaillon** [comment]
I agree, this would be a really great feature.

**Comment by jselis** [comment]
I agree too!!

**Comment by albermontes** [comment]
Yes please, other solution is make https://www.lightningdesignsystem.com/ in one single page so yo can  use the browser search. Now is very hard find something.

PD: SLDS is a great job!!! Thanks

**Comment by zokito** [comment]
+1

**Comment by kaelig** [comment]
Great suggestion.

On the public website, which is crawlable by Google, we have these easy-to-implement options:

- [Google Custom Search](https://cse.google.com/cse/?hl=en] (unfortunately the search field is pretty hard to style, so that's a tradeoff)
- a form that redirects users to Google, with a scoping on the slds site: https://www.google.com/#q=site:lightningdesignsystem.com+clarity

**Comment by kaelig** [comment]
In our latest update, we added a search field at the top of the navigation. Let us know what you think!
