### ISSUE TITLE
Is this a beta or can I use this for production?

### ISSUE THREAD

**Issue by eduardoinnorway** [salesforce-ux/design-system#524]
You should really considering of retesting EVERYTHING, it just feels super buggy right now. Icons that are super sized on load then small, a accordion that does not toggle, a select dropdown that does not behave properly, a date-picker that does not scale, and so on.

Regarding: https://www.lightningdesignsystem.com/components/overview

Just saying.

**Comment by istiti** [comment]
I completly agree. I think @salesforce should dedicate more time/developers into this because it’s awesome what work is already provided and we need to have a look this project could promise/be big success but if I must criticize I could say:

 I think exactly same as you and of course without bad faith. 

To be in production use I think this slds should have apple-mind « 99.999% » without any bugs.

It’s very dammage how team is away from this beautiful design.  Team is not close to users. We have no roadmap, no iteration/ interaction. This project could be in each  professionnal tools because of the look n feel looks very serious beautiful design.

Please any inputs here? From the holders and how can we vote to let salesforce add mores team members here


(Critics compared to angular project, typescript project)

**Comment by engai** [comment]
Hi @eduardoinnorway @istiti, thank you for your feedback. 

First and foremost, it is our goal to ship a high quality design system with the least amount of bugs possible. But we understand that bugs happen, and are working hard to strengthen our testing framework. 

At the same time, we also hope to improve our relationship with our customers on Github & other communication channels. Please continue to file issues with specific bugs you'd like to see fixed, and our team will make a better effort to respond quickly to them.

**Comment by eduardoinnorway** [comment]
Hi @engai Thank you for answering this issues to me and @istiti .

I think that this bugs or misunderstandings should not be there in the first place for having a big company like Salesforce backing it up.

Lets just look into one case like Accordion: https://www.lightningdesignsystem.com/components/accordion/

- I think that a Style-guide that has a component library, even if it is only style, you should at least implement interaction on something like an accordion.
- If "Variants" is only one, then why do you use a radio button? Use proper HTML.
- Now if I press the "Base" radio button it will act as it should, but it also disables ".slds-is-open" checkbox. Now, what is that behaviour?
- And what does the arrow down icon buttons at the right side actually do? Is that a part of the style guide, some feature to show code? Or is it some usability/design feature to select something in the accordion that is not documented?
- And fixing the "big then go small svg" issue, is something that should have been fixed and noticed by anyone working in this project, with setting for example max-width on that icon class.
- And so on ...

Overall to me, watching the video and expectations I got from the landing page I was expecting something AWESOME. But the component library feels like it was coded by the Designers rather than the Senior front-end developers as it should have.

The user group for something like this, is people like me, so I suggest you setup a user reference group and gather all the information you need to go beyond what you have today, with "user tests". If you think you will get all this by people doing "file issues", you are on for a long road, people are lazy, they will mostly spot everything I see an then move on to something that feels more stable without any "file issues".

Anyways, I really like the initiative and ambition, so that is the reason I take time to give "positive improvement suggestions". Keep up the hard work.

**Comment by istiti** [comment]
Salesforce slds lib  is on my watching list, yes I think too this is done by designer not truth front developer imo.

Company like salesforce must dedicate more developers more time to reach developers, because it’s dammage actually how slds is going forward, i really hope salesforce manager will think abiut it and put more works here because they can success and be in first place as UI UX for applications’ company in web developements !

Hope this will be considered and we will see change asap

**Comment by engai** [comment]
@eduardoinnorway In terms of the language/layout we use for components and their variants/modifiers, we understand that our current standard approach may not work for all components (like those with only a base variant), and are looking for ways to improve it. As for implementation on components such as the Accordion, we stay away from adding functionality in order to stay platform agnostic. What works for you may not work for others. That being said, we're looking to make it more clear as to how components should behave at a user experience level.

(+ @istiti) Generally, we pour a lot of our resources into building the system itself, but will work to make the documentation experience much more enjoyable. We have a great UX team looking for ways to better understand our users and Github issues is just one of the ways we do so.

Thank you both for your valuable feedback! We appreciate that you are voicing out your concerns and will take them into consideration moving forward.
