### ISSUE TITLE
static ressources with new syntax only!

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#546]
After opening 
https://github.com/salesforce-ux/design-system/issues/486 and https://github.com/salesforce-ux/design-system/issues/467 

Can we be smarter and propose static ressources (css files) on https://www.lightningdesignsystem.com vebsite in three versions:
1. slds_new_syntax_only.css
2. slds_old_syntax_only.css
3. slds_new_and_old_syntax.css

Since 1 year we still have duplicated file size in our project because of breaking change in BEM syntax. And we only have this third point I mentioned.
(no scss)

Thanks

**Comment by istiti** [comment]
Due to this I get this score with [Lighthouse] : 
![image](https://user-images.githubusercontent.com/2789203/40221870-036f14b6-5a7e-11e8-9cf6-ae41232e2c57.png)


My file compressed could be 2x smaller with link to download static ressources without old BEM syntax

**Comment by engai** [comment]
Hi @istiti, thank you for sharing your concerns and for the feature request.

Unfortunately, we do not plan on providing a variations of our static resource. The reason being that we primarily support the Salesforce platform and our teams need both the old and new BEM syntax. Moving forward, new components today are being built with the new syntax, but there are still use cases that utilize the old BEM that we must support. Both will remain in our static resource until the Salesforce platform no longer requires it.

We've provided you with regex in the past to remove the old syntax for your use case. Please feel free to use that in order to bring your file size down. Since the CSS classes are comma separated, I don't think that you will necessarily see a 2x decrease in file size.
