### ISSUE TITLE
New button types not following naming pattern

### ISSUE THREAD

**Issue by joshsylvester** [salesforce-ux/design-system#549]
In release [v2.6.0](https://github.com/salesforce-ux/design-system/releases/tag/v2.6.0), some new styles were added for many components. For button, the styles do not follow the normal class naming pattern.  Typically, the design system follows a pattern of `slds-button--{type}` AND `slds-button--{type}`, but for the new style (`outline-brand`) this naming convention was not followed.

Any reason for the inconsistency?

As a user consuming the styles in question, which class name convention should we be using?

Related code is here: 
https://github.com/salesforce-ux/design-system/blob/master/ui/components/buttons/base/_index.scss#L164

```
/**
 * Creates the brand blue Salesforce style
 *
 * @selector .slds-button_brand
 * @restrict .slds-button
 * @modifier
 * @group theme
 */
.slds-button_brand,
.slds-button--brand {
  @include button;
  @include button-brand;

  &[disabled] {
    background: $brand-disabled;
    border-color: $brand-disabled;
    color: $color-text-button-brand-disabled;
  }
}

/**
 * Creates the outlined button with the brand color
 *
 * @selector .slds-button_outline-brand
 * @restrict .slds-button
 * @modifier
 * @group theme
 */
.slds-button_outline-brand {
  @include button;
  @include button-base;
  border-color: $brand-accessible;

  &[disabled] {
    background: $brand-disabled;
    border-color: $brand-disabled;
    color: $color-text-button-brand-disabled;
  }
}
```

**Comment by stefsullrew** [comment]
We originally used the more common double dash BEM naming. But since you can't comment out a `--` in XML without an error, we had to use the original BEM naming of a single underscore (`_`).

At the time we made the change, we added the additional BEM style to existing components:
.slds-button_brand,
.slds-button--brand { }

However, from that point forward, anything new we create, we use the single underscore only. (The double-dash is simply for backward compatibility.)

Hopefully that helps... Cheers!

**Comment by joshsylvester** [comment]
@stefsullrew Thanks for the update, sorry for the confusion.

**Comment by stefsullrew** [comment]
No worries... it IS confusing. :)
