### ISSUE TITLE
Fallback support for IE10 & IE9

### ISSUE THREAD

**Issue by jrots** [salesforce-ux/design-system#55]
Hi, wanted to start using the lightning system for a new app I'm developing, 
but the hard requirement of having IE11 or the latest version of chrome/ firefox scares me a bit. 

I think especially in the corporate world where there are companies that can't upgrade all of their systems  that easily will still make use of older browsers. 

Are there any plans to support some fallback css/ js to make sure the pages aren't completely broken on those systems?

**Comment by stefsullrew** [comment]
Will your app be used outside the Lightning experience? SLDS uses the same browser levels as Lightning itself uses. (That said, some things will work just fine and have some fallbacks built in, but the place you'll run into the most trouble is likely the flexbox grids.)

I did talk to some folks at Dreamforce who have customers that will require older browser support. We can certainly add it as an enhancement request if there are enough people that need it. Cheers.

**Comment by rodriguezartav** [comment]
My 2 cents as a partner that's trying to use the design-system ( aka selling inside my org ), is that this seems like a deadlock. Because Lightning Experience is still not going to be massively adopted which means that whatever we build is going to need fallback support anyways during transition.

Being so limited in browser support makes you feel like walking on thin ice - because that "battle" that Salesforce will take with their users to upgrade has not began yet - so having it this way will turn trouble into the shoulders of individual developers .


+1

**Comment by kaelig** [comment]
Closing this as there we no near future plans to provide support for older browsers.
