### ISSUE TITLE
gutters misunderstanding

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#558]
I'm using statics ressoruces (css) in v2.6.1 but this always happends in previous version too.

Like slds-quickstarter repo example  i use grid and have some problems with gutters:
currently structure : 
![image](https://user-images.githubusercontent.com/2789203/41143842-1bb20b90-6afb-11e8-8895-b09adf4fbca6.png)
result:
![image](https://user-images.githubusercontent.com/2789203/41144139-2c19c3a0-6afc-11e8-8a37-23dd5a5ed7a6.png)

With this I always have horizontal scrolling (due to negative margin).

What is correct way to avoid this little horizontal scroll and keep left and right margin of slds-gutters visible.  Of what is motivation to have this, does my parent here `slds-col fullwidth  slds-scrollable` need have padding but how know the correct padding size ro avoid horizontal gutters in docs thanks 

cc @engai

**Comment by engai** [comment]
Hi @istiti, our intentions with `slds-gutters` is to add "gutters" or "spacing" in between each flex item with the class `slds-col`. We do this by adding horizontal padding to each column. Since doing so adds extra spacing to the ends of the container (which we don't want), we use negative margins on the `slds-gutters` element to bring our columns back out, and have them align with the edges of the container.

Unfortunately, this is creating an overflow, and causing unwanted scroll bars in your implementation. If you'd like the padding on the very ends of the container, I would suggest that you use `slds-p-horizontal_[size]` on each of your column elements instead of `slds-gutters`. This should fix your scroll issue.

Please let me know if you have any further questions.

**Comment by istiti** [comment]
yes but what I need to do to avoid overflow ? And glutters add only horizontal padding  but what about vertical ? because when I resize all my block are glued together, dont we need add  horizontal and vertical to slds-gutters 
cc @engai

**Comment by engai** [comment]
@istiti I'm not sure I fully understand what you're trying to achieve here. Could you please provide a Codepen that would allow me to debug your issue?

As for vertical padding, `slds-gutters` provides 'gutters' between columns, not rows.

**Comment by engai** [comment]
@istiti any updates here?
