### ISSUE TITLE
Selected-with-Hover-State component

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system#566]
On documentation https://www.lightningdesignsystem.com/components/buttons/#Selected-with-Hover-State

Here:
![hoverbug](https://user-images.githubusercontent.com/2789203/42371045-98be2fc8-810e-11e8-956c-bc0f6874b0d5.gif)

Or: 
![hoverbug2](https://user-images.githubusercontent.com/2789203/42371140-ddcd7812-810e-11e8-8b7b-f830ddf7050f.gif)

**Comment by engai** [comment]
Hi @istiti, thanks for pointing this out. Since the the width of the button changes on hover in both cases, these example suffer from some CSS jitter as you've pointed out.

I'm not sure if there is a good fix for this, but we're open to suggestions if you have any. At the end of the day, it's a CSS side-effect of having hover effects that change width (due to the length of text). Though there is a bit of jitter in a small area, i'd say the interaction model that it allows for is a good trade off for the user.

From a component library perspective, I don't believe we can set a fixed width for the Button. But, in your use case, that may be a good alternative as it will prevent the css jitter and allow for better alignment of your other columns.

**Comment by istiti** [comment]
@engai thanks dude for consideration :) hm wonder why this issue is marked as question ? you meant question from your side ? 

Yes your are right this is weird thing ^^, but to be honest we can be smarter here to handle this effect... and IMHO (without bad faith) Salesforce team shouldn't add buggy component and let people do this on their side.

I didn't investigate more, feel free to  find  better solution but we couldn't allow this as official documentation:
## Current
![ezgif-2-f1a6cd07aa](https://user-images.githubusercontent.com/2789203/42415537-edd0b956-8251-11e8-8db8-907df53512dd.gif)

## After fix
![ezgif-2-a02fd00fad](https://user-images.githubusercontent.com/2789203/42415546-443f3c68-8252-11e8-9365-474bb32b2dbe.gif)


We can relativly consider this solution as "hack" but it is better than current behavior don't you think, little bit more serious :) ? 
My idea is always keep width of current showed span (here `<span class="slds-text-selected">`)
And instead havin `.slds-is-selected:hover .slds-text-selected{display:none}`on hover state just set `height:0px;` 

of course on .slds-text-selected we need apply `overflow:hidden` 

![capture d ecran 2018-07-08 a 02 05 09](https://user-images.githubusercontent.com/2789203/42415582-e98c941c-8253-11e8-80ee-80735a5daa4f.png)


I know you need investigate in intern noproblem to me if you close issue just want notify documentation bug

**Comment by engai** [comment]
@istiti I've labeled it as a question since I was not certain if it was a bug that needed addressing on our end. Initially, the issue seemed like a question asking "why?".

I'll touch base with the rest of the team & circle back with whether or not we would like to tackle this bug.

cc: @brandonferrua @stefsullrew

**Comment by stefsullrew** [comment]
Thanks for the input @istiti ... 

Our buttons are built without widths. They're based on the content inside. Since we build our blueprints for platform use, with no ability to know how people will use it when there is localization or different words used inside. We also don't provide JS. 

So to that end, we suggest that if you know your use case, you should feel free to add the widest width to the button, use JS to measure and add the width inline, or set your displays/heights/etc to work for your use case. This is not something we will change from the SLDS side since it requires the user to know how they're using it and respond accoringly.

**Comment by istiti** [comment]
Thanks a lot for answer, maybe i misunderstand you response, Did you consider my screenshot https://user-images.githubusercontent.com/2789203/42415582-e98c941c-8253-11e8-80ee-80735a5daa4f.png

Wonder where you see i speak about fixed width  :) , here we don’t need fixed width and we don’t need js to have better behavior.  

In your platform or not if it is in a browser you get this css bug if we could call it bug. My idea would be to keeep automatically  for first displayed element the width if hovered element is smaller! This will change nothing in your platform it could just fix behavior ! 

Can you double chek solution, thanks
