### ISSUE TITLE
Readme has broken link to more complex example of annotations

### ISSUE THREAD

**Issue by jepedo** [salesforce-ux/design-system#573]
The readme has a link for a more complex example of annotations that does not work  https://github.com/salesforce-ux/design-system-internal/blob/summer-17/ui/components/combobox/base/_index.scss. I was hoping to find details on how to properly leverage LDS to create your own branded lightning experience. Installing the design system is straight forward and I can make changes to ui/core, ui/components etc... but I cannot find documentation on how to get that crisp new branding lightning design into your Salesforce org and community. 

There is quite a robust list of design tokens https://www.lightningdesignsystem.com/design-tokens/ but what is not clear is how your modify those to adhere to your own brands. I see that in Dev you can override standard tokens https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/tokens_standard_overrides.htm. When will this be available in production. Is there another way to override standard tokens? It seems like the most logical way to implement your own brand into Lightning.

**Comment by engai** [comment]
Hi @jepedo, thanks you for sharing your concerns. A fix for the link you've shared will be coming in our next Winter '19 release. 

As for branding your own org/community, have you tried to utilize the Theming feature within Setup? This is our built in method to add your brand logo and colors to your org.

**Comment by engai** [comment]
Hi @jepedo, we've removed the broken annotation links with https://github.com/salesforce-ux/design-system/commit/bf75f472859320f0165c4a63de894e10b19ccecc.

As for the branding question, we would suggest using the themeing feature in lightning. This provides a standard method to leverage our branding tokens, that allows you to brand the entire Salesforce Lightning Experience rather than just a specific component.
