### ISSUE TITLE
Change icon used in Checkbox Toggle or Checkbox Button

### ISSUE THREAD

**Issue by tylerzika** [salesforce-ux/design-system#574]
There is a check mark icon used when the Checkbox Toggle is Enabled:

https://www.lightningdesignsystem.com/components/checkbox-toggle/

There is a plus or check used depending on the state of the Checkbox Button:

https://www.lightningdesignsystem.com/components/checkbox-button/

Is there an out-of-the-box way to change these icons. I'd really like to use the Checkbox Toggle to change my view state, and have a 1 or 2 showing depending on the Checkbox Toggle state, instead of check mark.

**Comment by jimpdx** [comment]
We have a similar issue. The standard "checkbox" format is woefully inadequate for our mobile use case (and difficult to tap on). I find myself wanting to use "Checkbox Toggle" to represent our standard Checkbox fields and Survey questions. My developers are pushing back saying that it should only be used in a "cart context" to add/remove items as opposed to true/false. Could we get someone on the SLDS team to weigh in?

![image](https://user-images.githubusercontent.com/867051/44488231-12808b80-a60d-11e8-9fe6-742cb1d24a6e.png)

**Comment by engai** [comment]
Hey @tylerzika, thanks for your question. Since the styles in both the Checkbox Toggle and Checkbox Button are both driven by CSS and not static assets, there is no out of the box way to change these. Furthermore, I don't believe we should support the design pattern of replacing these checks with numbers to indicate that the option has been selected. The purpose of a checkbox input is to make a binary decision on what is described by the label. A number within the checkbox could be confusing from a usability perspective and for accessibility reasons.

I would suggest looking into other ways to achieve your goal here, such as creating a label separate from the checkbox that responds to the option selected in the checkbox.

**Comment by engai** [comment]
Hey @jimpdx, I believe that you have a great use case for a Checkbox Toggle. Semantically, the Checkbox Toggle is just an `<input>` of `type="checkbox"`, and could be used just like any other checkbox to make a true/false selection. I'm not sure why your devs think that they should only be used in a "cart context", but would love to hear more on that.

**Comment by jimpdx** [comment]
Thanks @engai. We ended up hacking the CSS to make the checkbox larger, which works OK. We particularly wanted it to be consistent with the height of other form inputs. Perhaps this could be considered in the standard SLDS roadmap:

![image](https://user-images.githubusercontent.com/867051/45328138-6cd78280-b50f-11e8-9f53-4d6866db0cc4.png)
