### ISSUE TITLE
Radio Group Styling Not Consistent With Other Form Tags

### ISSUE THREAD

**Issue by KrishnaBluewolf** [salesforce-ux/design-system#651]
The `lightning-radio-group` tag (https://developer.salesforce.com/docs/component-library/bundle/lightning-radio-group/example) had a bold label. Other lightning tags such as `lightning-combo-box` (https://developer.salesforce.com/docs/component-library/bundle/lightning-combobox/example) doesn't have a bold label.

We should have some mechanism on the `lightning-radio-group` tag to request a non-bold tag that is consistent with the other lightning form components. Otherwise it is result in glaring inconsistencies visually, and with Shadow DOM, I cannot apply my own styling to enable consistency.

Since the tags are driven based on SLDS markup, which doesn't offer this option today, I'm posting this issue here.

**Comment by alexiscordova** [comment]
Hi @KrishnaBluewolf, thanks for your question. What you're seeing for Radio Groups is a `<legend>` since the label is referring to multiple radio buttons, while the Combobox is using a `<label>` as it refers to a single input. Since both `legend` and `label` can be used simultaneously (see https://www.lightningdesignsystem.com/components/form%2Delement/#Horizontal-Alignment-2), we have bolded `legend`s to differentiate them.

Hope that helps!

**Comment by KrishnaBluewolf** [comment]
When you put these in a lightning form, the radio group shows up as bold label, while the other inputs aren't bold label. It really stands out in a way that it shouldn't stand out. From an end user perspective, it is one field.

**Comment by FinnArild** [comment]
I also think this does not make sense. In a form, you want a set of radio buttons or checkboxes look similar to your other fields. Until salesforce unf**s this up, you can use the following workaround: 
![image](https://user-images.githubusercontent.com/4902053/144894517-aea28090-2bed-482a-9633-6cbf6cf88b0e.png)
