### ISSUE TITLE
Replace colors and create custom slds theme. How?

### ISSUE THREAD

**Issue by sasha-t** [salesforce-ux/design-system#652]
Hi!
How I can replace colors and rebuild css files for create custom slds theme?
I don't found this information...

Thank you!

**Comment by alexiscordova** [comment]
Hi @sasha-t. This isn't currently supported in SLDS, which is why it's not documented anywhere. However, if you're using the source of SLDS, you can edit the files in `design-tokens/primitive/` which contain our GA tokens. You can read more about our tokens here https://www.lightningdesignsystem.com/design-tokens/

To rebuild SLDS with the new token values, run the `npm run full-start` command in your terminal.

Again, this isn't supported so there is no documentation on this topic. Good luck!
