### ISSUE TITLE
Font License

### ISSUE THREAD

**Issue by sanunes27** [salesforce-ux/design-system#669]
By reading the licenses agreements for the LDS, I understand that I can use it for any personal projects or even for commercial external purposes and distribution, following of course, the specifications of the license. But, when I read the Salesforce Font license, it seems that they only allow it to be used under a Salesforce Environment and I wonder if that's how I should interpret it? My goal is to use the LDS for an external app, with nothing to do with Salesforce and that I could potentially re-sell. Would I have to use another font if I want to use it commercially? Here is the snippet from the license in question:

1. License Grant

Subject to the terms of this Agreement and any other
applicable Salesforce terms, conditions, and acceptable use policies (AUPs),
We hereby grant to You a revocable, non-transferable, non-exclusive, and non-
sublicenseable limited license to, without modification, reproduce and use the
Font solely to create applications with the Salesforce Lightning Design System
**that run in Salesforce or on a Salesforce platform (e.g., Lightning, Heroku,
Visualforce) (“Applications”).**

**Comment by gelliott181** [comment]
The Salesforce Font is able to be (and has been) copyrighted as a Salesforce work. This leads to the license needing to protect their branding, to which the lawyers said (In many more words) "Ok, only useable with our products, otherwise it risks diluting or damaging the brand."

This approach is similar to Apple and their San Francisco font: 
> Limited License. Subject to the terms of this License, you may use the Apple Font solely for creating mock-ups of user interfaces to be used in software products running on Apple’s iOS or OS X operating systems, as applicable. The foregoing right includes the right to show the Apple Font in screen shots, images, mock-ups or other depictions, digital and/or print, of such software products running solely on iOS or OS X.

It totally makes sense for Apple, they control the platform the content is branded for at an OS level so it's inherently unavailable on non-Apple platforms legally.

For Salesforce, a web platform? Kinda breaks the whole scheme. I need a lawyer to verify my interpretation, but here it goes:
* You have an application built with, say, Angular, served from an AWS bucket, integrating with Salesforce over the rest API
 ** The Salesforce Font cannot be used because your application only integrates with Salesforce. It sits "next to" their platform.

* You have another application built in Angular, served from Heroku, that integrates with a Salesforce Competitor
 ** The Salesforce Font can be used because you're serving from a Salesforce platform. The branding dilution that Salesforce was trying to avoid happens as you are able to use this part of the Salesforce branding to provide a competitor's service under guise of being on the platform.

I think the fix is to put the lawyers back in their conference room with someone who understands the difference between hardware and web platforms until they come up with language that flips the legality of these two examples.

**Comment by kflournoy-sf** [comment]
Hi @sanunes27! I don't think that our team can officially answer this for you - you may want to contact Salesforce Legal about this question: https://www.salesforce.com/company/legal/
