### ISSUE TITLE
LWC Card + inner body padding issue

### ISSUE THREAD

**Issue by thiakil** [salesforce-ux/design-system#712]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

```html
<lightning-card title="foo">
    <div class="slds-card__body_inner">
        Content here
    </div>
</lightning-card>
```

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

I have often used the above pattern to add the body padding to an LWC based card, but this no longer works after the linked commit:

https://github.com/salesforce-ux/design-system/commit/4a3ebf9c3e2d59c19fd1655cc255f040a329ce1d#diff-40f7f129fedd2be31602714c7a908a60158b6a32179c8193a12b4f964160841eL89-R127

I appreciate this may be the "wrong" way to use it, but as we can't directly affect the LWC Card's `slds-card__body` div, it's (or was) the next best option to ensure the correct Card padding.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

Cards -> With padding

> Are any specific browsers impacted by this bug?

All

> Which version of the Salesforce Lightning Design System are you using?

Spring '22 Patch 5.1 Org (CS5)

> What steps and/or code are needed to reproduce this issue?

See above code snippet

> What did you expect to happen?

Horizontal padding to be added to the inner body element

> What actually happened?

No padding is added as it now expects to be adjusting the styling hook of the `slds-card__body` element

**Comment by alexiscordova** [comment]
Hi @thiakil,

Thanks for bringing this to our attention. You're right, it does look like our Lightning component doesn't match our SLDS blueprint, and now that we're using CSS Custom Properties it makes sense why this isn't working. Apologies for this! I'll pass this along to the relevant team(s) so we can get this addressed. cc @aneeshack4 @kflournoy-sf 

In the meantime, I believe there are two ways of fixing this on your end:
1. Add the `slds-card__body` class to your slotted content. e.g., `<div class="slds-card__body slds-card__body_inner">…</div>`. This isn't the most ideal solution as you're doubling up the body class, but due to [collapsing margins](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing) you won't get extra top and bottom margin. This should have the left/right padding on the body work.
2. Wrap your card in a div and use the following Styling Hooks: `--slds-c-card-body-spacing-inline-end` (padding-right) and `--slds-c-card-body-spacing-inline-start` (padding-left)` with a value of 1rem or equivalent token. This is how it _should_ be working internally, and this somewhat replicates that approach.

I tried both fixes in our LWC playground and they seem to do the trick, but if you run into problems please do reach out. Again, apologies for this issue.
